import { initDb, getDb } from './schema';

const sampleSignals = [
  {
    title: 'GPT-5 Demonstrates Emergent Reasoning Capabilities Beyond Human Benchmark',
    summary: 'OpenAI releases GPT-5 showing unprecedented reasoning abilities, scoring above 95th percentile on professional exams including bar, medical boards, and CFA. The model exhibits novel problem-solving approaches not present in training data.',
    source_name: 'OpenAI Blog',
    source_type: 'announcement',
    url: 'https://openai.com/research/gpt-5',
    publication_date: '2024-02-15',
    scan_date: '2024-02-16',
    topic_area: 'Artificial Intelligence',
    focus_area: 'Large Language Models',
    technology_area: 'Machine Learning',
    driver_trend: 'AI Capability Acceleration',
    signal_type: 'strong',
    geographic_relevance: 'Global',
    industry_relevance: 'All Industries',
    confidence_level: 5,
    novelty: 5,
    potential_impact: 5,
    time_horizon: 'now',
    status: 'published',
    tags: JSON.stringify(['LLM', 'OpenAI', 'AGI', 'reasoning']),
    analyst_notes: 'Critical signal. Monitor for regulatory responses and competitor reactions.'
  },
  {
    title: 'Google Quantum AI Achieves Error-Corrected Logical Qubit Milestone',
    summary: 'Google announces breakthrough in quantum error correction, demonstrating a logical qubit with error rates below the physical qubit threshold. This is a crucial step toward fault-tolerant quantum computing.',
    source_name: 'Nature',
    source_type: 'paper',
    url: 'https://nature.com/quantum-error-correction',
    publication_date: '2024-01-22',
    scan_date: '2024-01-23',
    topic_area: 'Quantum Computing',
    focus_area: 'Error Correction',
    technology_area: 'Quantum Hardware',
    driver_trend: 'Quantum Supremacy Race',
    signal_type: 'strong',
    geographic_relevance: 'USA',
    industry_relevance: 'Cryptography, Finance, Pharmaceuticals',
    confidence_level: 4,
    novelty: 5,
    potential_impact: 5,
    time_horizon: '3-5yr',
    status: 'published',
    tags: JSON.stringify(['quantum', 'error-correction', 'Google', 'hardware']),
    analyst_notes: 'Landmark result. Fault-tolerant QC timeline may accelerate significantly.'
  },
  {
    title: 'Salt Typhoon APT Group Compromises Major US Telecom Infrastructure',
    summary: 'Chinese state-sponsored threat actor Salt Typhoon gains persistent access to multiple major US telecommunications providers, intercepting sensitive communications of government officials and political figures.',
    source_name: 'CISA Advisory',
    source_type: 'regulatory',
    url: 'https://cisa.gov/salt-typhoon-advisory',
    publication_date: '2024-03-01',
    scan_date: '2024-03-02',
    topic_area: 'Cybersecurity',
    focus_area: 'Nation-State Threats',
    technology_area: 'Network Security',
    driver_trend: 'Geopolitical Cyber Conflict',
    signal_type: 'strong',
    geographic_relevance: 'USA',
    industry_relevance: 'Telecommunications, Government',
    confidence_level: 5,
    novelty: 3,
    potential_impact: 5,
    time_horizon: 'now',
    status: 'published',
    tags: JSON.stringify(['APT', 'China', 'telecom', 'espionage', 'CISA']),
    analyst_notes: 'Immediate action required for telecom clients. Review network segmentation.'
  },
  {
    title: 'Perovskite Solar Cell Efficiency Reaches 33.9% in Lab Setting',
    summary: 'NREL-certified efficiency record broken again for tandem perovskite-silicon solar cells. Commercial viability concerns around durability addressed with new encapsulation techniques showing 25-year lifetime projections.',
    source_name: 'Nature Energy',
    source_type: 'paper',
    url: 'https://nature.com/energy/perovskite-efficiency',
    publication_date: '2024-02-08',
    scan_date: '2024-02-09',
    topic_area: 'Climate Technology',
    focus_area: 'Solar Energy',
    technology_area: 'Photovoltaics',
    driver_trend: 'Energy Transition',
    signal_type: 'emerging',
    geographic_relevance: 'Global',
    industry_relevance: 'Energy, Manufacturing',
    confidence_level: 4,
    novelty: 4,
    potential_impact: 4,
    time_horizon: '3-5yr',
    status: 'under_review',
    tags: JSON.stringify(['solar', 'perovskite', 'efficiency', 'clean-energy']),
    analyst_notes: 'Watch for commercialization announcements from LONGi and First Solar.'
  },
  {
    title: 'NVIDIA Blackwell B200 GPU Ships 30x Inference Performance Improvement',
    summary: 'NVIDIA announces Blackwell architecture with 30x improvement in LLM inference performance versus Hopper. New NVLink scale to 576 GPUs enables unprecedented model sizes. Demand already exceeding supply through 2025.',
    source_name: 'NVIDIA GTC Keynote',
    source_type: 'announcement',
    url: 'https://nvidia.com/gtc/blackwell',
    publication_date: '2024-03-18',
    scan_date: '2024-03-19',
    topic_area: 'Artificial Intelligence',
    focus_area: 'AI Infrastructure',
    technology_area: 'GPU Computing',
    driver_trend: 'AI Hardware Arms Race',
    signal_type: 'strong',
    geographic_relevance: 'Global',
    industry_relevance: 'Technology, Cloud Computing',
    confidence_level: 5,
    novelty: 4,
    potential_impact: 5,
    time_horizon: 'now',
    status: 'published',
    tags: JSON.stringify(['NVIDIA', 'GPU', 'AI', 'Blackwell', 'inference']),
    analyst_notes: 'Massive implication for AI compute cost curves. Could democratize LLM deployment.'
  },
  {
    title: 'EU AI Act Enters into Force with Phased Compliance Timeline',
    summary: "The European Union AI Act is formally published, establishing the world's first comprehensive AI regulation framework. High-risk AI systems face strict requirements. General-purpose AI models above threshold compute face additional obligations.",
    source_name: 'Official Journal of the EU',
    source_type: 'regulatory',
    url: 'https://eur-lex.europa.eu/ai-act',
    publication_date: '2024-08-01',
    scan_date: '2024-08-02',
    topic_area: 'Artificial Intelligence',
    focus_area: 'AI Governance',
    technology_area: 'Policy & Regulation',
    driver_trend: 'AI Regulation Wave',
    signal_type: 'established',
    geographic_relevance: 'Europe',
    industry_relevance: 'All Industries',
    confidence_level: 5,
    novelty: 2,
    potential_impact: 5,
    time_horizon: '1-2yr',
    status: 'triaged',
    tags: JSON.stringify(['EU', 'regulation', 'compliance', 'AI-Act']),
    analyst_notes: 'Critical for all EU-facing products. Begin compliance gap analysis immediately.'
  },
  {
    title: 'Arm-Based Edge AI Chips Achieve Sub-1W LLM Inference for IoT',
    summary: 'New class of specialized edge AI processors from multiple vendors achieve on-device LLM inference for 7B parameter models at under 1 watt. Enables AI assistants in battery-powered IoT devices without cloud connectivity.',
    source_name: 'IEEE Spectrum',
    source_type: 'article',
    url: 'https://spectrum.ieee.org/edge-ai-chips-2024',
    publication_date: '2024-04-11',
    scan_date: '2024-04-12',
    topic_area: 'Edge Computing',
    focus_area: 'Edge AI',
    technology_area: 'Semiconductors',
    driver_trend: 'Edge Intelligence',
    signal_type: 'emerging',
    geographic_relevance: 'Global',
    industry_relevance: 'IoT, Consumer Electronics, Industrial',
    confidence_level: 3,
    novelty: 5,
    potential_impact: 4,
    time_horizon: '1-2yr',
    status: 'triaged',
    tags: JSON.stringify(['edge-AI', 'IoT', 'inference', 'semiconductor', 'low-power']),
    analyst_notes: 'Transformative for disconnected and privacy-sensitive use cases.'
  },
  {
    title: 'Anthropic Constitutional AI Method Extended to Reinforcement Learning',
    summary: 'Anthropic publishes research extending Constitutional AI approach to pure RL settings, showing AI systems can learn human values without extensive RLHF labeling. Potential to dramatically reduce alignment costs.',
    source_name: 'Anthropic Research',
    source_type: 'paper',
    url: 'https://anthropic.com/research/constitutional-rl',
    publication_date: '2024-05-03',
    scan_date: '2024-05-04',
    topic_area: 'Artificial Intelligence',
    focus_area: 'AI Safety & Alignment',
    technology_area: 'Reinforcement Learning',
    driver_trend: 'AI Alignment Research',
    signal_type: 'emerging',
    geographic_relevance: 'Global',
    industry_relevance: 'Technology',
    confidence_level: 3,
    novelty: 5,
    potential_impact: 5,
    time_horizon: '3-5yr',
    status: 'new',
    tags: JSON.stringify(['Anthropic', 'alignment', 'safety', 'RLHF', 'Constitutional-AI']),
    analyst_notes: 'Early stage but highly significant for long-term AI safety.'
  },
  {
    title: 'Carbon Capture Direct Air Capture Cost Drops Below $300/ton',
    summary: '1PointFive and Climeworks report new facility designs achieving DAC costs below $300/ton CO2, down from $1000+. New sorbent materials and process heat recovery account for majority of cost reduction.',
    source_name: 'Energy & Environmental Science',
    source_type: 'paper',
    url: 'https://rsc.org/journals/EES/DAC-cost',
    publication_date: '2024-03-28',
    scan_date: '2024-03-29',
    topic_area: 'Climate Technology',
    focus_area: 'Carbon Removal',
    technology_area: 'Direct Air Capture',
    driver_trend: 'Net Zero Race',
    signal_type: 'emerging',
    geographic_relevance: 'Global',
    industry_relevance: 'Energy, Heavy Industry, Finance',
    confidence_level: 4,
    novelty: 4,
    potential_impact: 4,
    time_horizon: '3-5yr',
    status: 'under_review',
    tags: JSON.stringify(['DAC', 'carbon-capture', 'climate', 'cost-reduction']),
    analyst_notes: 'Key milestone toward economic viability. Track voluntary carbon market pricing.'
  },
  {
    title: 'Post-Quantum Cryptography NIST Standards Finalized',
    summary: 'NIST finalizes three post-quantum cryptographic standards: ML-KEM (CRYSTALS-Kyber), ML-DSA (CRYSTALS-Dilithium), and SLH-DSA (SPHINCS+). Organizations should begin migration planning immediately ahead of quantum threat.',
    source_name: 'NIST',
    source_type: 'regulatory',
    url: 'https://nist.gov/pqc-standards',
    publication_date: '2024-08-13',
    scan_date: '2024-08-14',
    topic_area: 'Cybersecurity',
    focus_area: 'Cryptography',
    technology_area: 'Post-Quantum Cryptography',
    driver_trend: 'Quantum Threat Preparation',
    signal_type: 'established',
    geographic_relevance: 'USA',
    industry_relevance: 'All Industries',
    confidence_level: 5,
    novelty: 2,
    potential_impact: 5,
    time_horizon: '1-2yr',
    status: 'published',
    tags: JSON.stringify(['NIST', 'post-quantum', 'cryptography', 'PQC', 'standards']),
    analyst_notes: 'Begin crypto agility assessment for all products. Long migration cycle ahead.'
  },
  {
    title: 'Microsoft Azure Launches Quantum-Inspired Optimization Service',
    summary: 'Microsoft brings quantum-inspired optimization algorithms to Azure as a managed service, targeting supply chain, logistics, and financial portfolio optimization. Claims 1000x speedup vs classical for certain problem classes.',
    source_name: 'Microsoft Azure Blog',
    source_type: 'announcement',
    url: 'https://azure.microsoft.com/blog/quantum-optimization',
    publication_date: '2024-02-28',
    scan_date: '2024-03-01',
    topic_area: 'Quantum Computing',
    focus_area: 'Quantum Optimization',
    technology_area: 'Cloud Services',
    driver_trend: 'Quantum Advantage Applications',
    signal_type: 'emerging',
    geographic_relevance: 'Global',
    industry_relevance: 'Supply Chain, Finance, Logistics',
    confidence_level: 3,
    novelty: 3,
    potential_impact: 3,
    time_horizon: '1-2yr',
    status: 'triaged',
    tags: JSON.stringify(['Microsoft', 'Azure', 'quantum', 'optimization', 'cloud']),
    analyst_notes: 'Practical near-term application of quantum techniques. Evaluate for supply chain clients.'
  },
  {
    title: 'AI-Powered Drug Discovery Platform Identifies Novel Antibiotic Class',
    summary: 'MIT-Harvard collaboration using graph neural networks discovers new antibiotic class effective against pan-resistant bacteria. AI screened 100M+ compounds in weeks, found 283 candidates. Two entering Phase I trials.',
    source_name: 'Cell',
    source_type: 'paper',
    url: 'https://cell.com/ai-antibiotic-discovery',
    publication_date: '2024-05-20',
    scan_date: '2024-05-21',
    topic_area: 'Artificial Intelligence',
    focus_area: 'AI in Healthcare',
    technology_area: 'Drug Discovery',
    driver_trend: 'AI-Accelerated Science',
    signal_type: 'strong',
    geographic_relevance: 'Global',
    industry_relevance: 'Pharmaceuticals, Healthcare',
    confidence_level: 4,
    novelty: 5,
    potential_impact: 5,
    time_horizon: '3-5yr',
    status: 'under_review',
    tags: JSON.stringify(['drug-discovery', 'antibiotic', 'GNN', 'healthcare', 'MIT']),
    analyst_notes: 'Major validation of AI drug discovery. Monitor clinical trial progress.'
  },
  {
    title: '5G Private Networks Enable Real-Time Robotic Control in Manufacturing',
    summary: 'BMW and Siemens deploy 5G campus networks achieving <1ms latency for robotic control systems, replacing wired connections. Enables dynamic reconfiguration of factory floors. 40% setup time reduction reported.',
    source_name: 'Manufacturing Engineering',
    source_type: 'article',
    url: 'https://sme.org/5g-robotic-manufacturing',
    publication_date: '2024-04-05',
    scan_date: '2024-04-06',
    topic_area: 'Edge Computing',
    focus_area: 'Industrial IoT',
    technology_area: '5G Networks',
    driver_trend: 'Industry 4.0',
    signal_type: 'established',
    geographic_relevance: 'Europe',
    industry_relevance: 'Manufacturing, Automotive',
    confidence_level: 4,
    novelty: 2,
    potential_impact: 3,
    time_horizon: 'now',
    status: 'published',
    tags: JSON.stringify(['5G', 'manufacturing', 'robotics', 'IIoT', 'BMW']),
    analyst_notes: 'Mature deployment signal. Good case study for manufacturing clients.'
  },
  {
    title: 'Ransomware Groups Adopt AI for Automated Vulnerability Discovery',
    summary: 'Security researchers document ransomware groups using LLM-assisted fuzzing to discover zero-days 10x faster than manual methods. New group RansomGPT monetizing AI capabilities as-a-service to criminal affiliates.',
    source_name: 'CrowdStrike Intelligence',
    source_type: 'article',
    url: 'https://crowdstrike.com/intelligence/ransomgpt',
    publication_date: '2024-06-10',
    scan_date: '2024-06-11',
    topic_area: 'Cybersecurity',
    focus_area: 'Threat Intelligence',
    technology_area: 'AI Security',
    driver_trend: 'AI-Augmented Attacks',
    signal_type: 'strong',
    geographic_relevance: 'Global',
    industry_relevance: 'All Industries',
    confidence_level: 4,
    novelty: 4,
    potential_impact: 5,
    time_horizon: 'now',
    status: 'published',
    tags: JSON.stringify(['ransomware', 'AI', 'zero-day', 'threat-intelligence', 'LLM']),
    analyst_notes: 'Significant escalation in threat landscape. Update patch prioritization frameworks.'
  },
  {
    title: 'Grid-Scale Iron-Air Battery Storage Achieves 100-Hour Duration',
    summary: 'Form Energy deploys commercial-scale iron-air batteries achieving 100-hour storage duration at $20/kWh capital cost. Technology uses reversible rusting reaction. Orders booked from 3 US utilities for 2025 deployment.',
    source_name: 'BloombergNEF',
    source_type: 'article',
    url: 'https://bloombergnef.com/iron-air-battery-grid',
    publication_date: '2024-07-14',
    scan_date: '2024-07-15',
    topic_area: 'Climate Technology',
    focus_area: 'Energy Storage',
    technology_area: 'Battery Technology',
    driver_trend: 'Grid Decarbonization',
    signal_type: 'strong',
    geographic_relevance: 'USA',
    industry_relevance: 'Energy, Utilities',
    confidence_level: 4,
    novelty: 5,
    potential_impact: 5,
    time_horizon: '1-2yr',
    status: 'under_review',
    tags: JSON.stringify(['battery', 'grid-storage', 'iron-air', 'Form-Energy', 'utilities']),
    analyst_notes: 'Potential game-changer for long-duration storage. Watch deployment results.'
  },
  {
    title: 'Federated Learning Standard Proposed for Cross-Hospital Medical AI',
    summary: 'IEEE working group releases draft standard for federated learning in healthcare settings, addressing HIPAA compliance, model poisoning defenses, and audit trails. 47 hospital networks participating in pilot.',
    source_name: 'IEEE Standards',
    source_type: 'regulatory',
    url: 'https://standards.ieee.org/federated-learning-health',
    publication_date: '2024-09-05',
    scan_date: '2024-09-06',
    topic_area: 'Artificial Intelligence',
    focus_area: 'Healthcare AI',
    technology_area: 'Federated Learning',
    driver_trend: 'Privacy-Preserving AI',
    signal_type: 'emerging',
    geographic_relevance: 'USA',
    industry_relevance: 'Healthcare, Technology',
    confidence_level: 3,
    novelty: 3,
    potential_impact: 4,
    time_horizon: '3-5yr',
    status: 'new',
    tags: JSON.stringify(['federated-learning', 'healthcare', 'HIPAA', 'privacy', 'IEEE']),
    analyst_notes: 'Important for healthcare AI deployments across institutions.'
  },
  {
    title: 'Satellite Internet Constellation Achieves 50ms Global Latency',
    summary: 'SpaceX Starlink V3 constellation with laser inter-satellite links achieves median 50ms latency globally including polar regions. Enables real-time applications in previously unserved areas. 4M+ subscribers as of Q2 2024.',
    source_name: 'Ars Technica',
    source_type: 'article',
    url: 'https://arstechnica.com/starlink-v3-latency',
    publication_date: '2024-05-30',
    scan_date: '2024-05-31',
    topic_area: 'Edge Computing',
    focus_area: 'Connectivity',
    technology_area: 'Satellite Communications',
    driver_trend: 'Global Connectivity',
    signal_type: 'established',
    geographic_relevance: 'Global',
    industry_relevance: 'Telecommunications, Maritime, Aviation',
    confidence_level: 5,
    novelty: 2,
    potential_impact: 3,
    time_horizon: 'now',
    status: 'triaged',
    tags: JSON.stringify(['Starlink', 'satellite', 'connectivity', 'SpaceX', 'LEO']),
    analyst_notes: 'Mature signal. Enables distributed edge deployments in remote locations.'
  },
  {
    title: 'Neuromorphic Computing Chip Processes Vision Tasks at 1000x Efficiency',
    summary: 'Intel Loihi 3 demonstrates real-time video object detection using 1000x less energy than GPU equivalent. Uses spiking neural network architecture mimicking biological neurons. Limited programmability remains challenge.',
    source_name: 'Intel Research',
    source_type: 'paper',
    url: 'https://intel.com/research/loihi-3-neuromorphic',
    publication_date: '2024-06-22',
    scan_date: '2024-06-23',
    topic_area: 'Edge Computing',
    focus_area: 'Neuromorphic Computing',
    technology_area: 'Novel Architectures',
    driver_trend: 'Brain-Inspired Computing',
    signal_type: 'weak',
    geographic_relevance: 'Global',
    industry_relevance: 'Technology, Defense, Robotics',
    confidence_level: 2,
    novelty: 5,
    potential_impact: 4,
    time_horizon: '5+yr',
    status: 'new',
    tags: JSON.stringify(['neuromorphic', 'Intel', 'Loihi', 'spiking-neural-network', 'energy-efficient']),
    analyst_notes: 'Early-stage but extremely interesting. Monitor research progress quarterly.'
  },
  {
    title: 'Zero Trust Architecture Mandated for US Federal Agencies',
    summary: 'OMB Memorandum M-24-04 requires all federal agencies achieve Zero Trust Architecture maturity level 4 by end of FY2025. Estimated $11B in additional federal spending on identity, network, and data security.',
    source_name: 'OMB',
    source_type: 'regulatory',
    url: 'https://whitehouse.gov/omb/m-24-04',
    publication_date: '2024-01-10',
    scan_date: '2024-01-11',
    topic_area: 'Cybersecurity',
    focus_area: 'Zero Trust',
    technology_area: 'Identity & Access Management',
    driver_trend: 'Federal Cybersecurity Push',
    signal_type: 'strong',
    geographic_relevance: 'USA',
    industry_relevance: 'Government, Defense Contractors',
    confidence_level: 5,
    novelty: 2,
    potential_impact: 4,
    time_horizon: '1-2yr',
    status: 'published',
    tags: JSON.stringify(['zero-trust', 'federal', 'OMB', 'government', 'IAM']),
    analyst_notes: 'Direct spending opportunity for ZTA vendors and system integrators.'
  },
  {
    title: 'Liquid Cooling Becomes Standard for Hyperscale AI Data Centers',
    summary: 'Major cloud providers announce liquid cooling as default for new GPU cluster deployments. Water cooling enables 3x compute density vs air-cooled racks. New standards emerging for coolant distribution and maintenance.',
    source_name: 'Data Center Dynamics',
    source_type: 'article',
    url: 'https://datacenterdynamics.com/liquid-cooling-standard',
    publication_date: '2024-07-28',
    scan_date: '2024-07-29',
    topic_area: 'Edge Computing',
    focus_area: 'Data Center Infrastructure',
    technology_area: 'Cooling Technology',
    driver_trend: 'AI Infrastructure Scaling',
    signal_type: 'established',
    geographic_relevance: 'Global',
    industry_relevance: 'Technology, Real Estate',
    confidence_level: 5,
    novelty: 1,
    potential_impact: 3,
    time_horizon: 'now',
    status: 'triaged',
    tags: JSON.stringify(['liquid-cooling', 'data-center', 'GPU', 'infrastructure', 'hyperscale']),
    analyst_notes: 'Infrastructure signal. Impacts facility design and operational costs.'
  },
  {
    title: 'China Develops Homegrown 7nm AI Chip Bypassing Export Controls',
    summary: 'SMIC and Huawei demonstrate 7nm class AI training chip achieving 80% of H100 performance, developed entirely with domestic tooling. Questions about long-term effectiveness of US export controls.',
    source_name: 'Reuters',
    source_type: 'article',
    url: 'https://reuters.com/china-7nm-chip',
    publication_date: '2024-08-20',
    scan_date: '2024-08-21',
    topic_area: 'Artificial Intelligence',
    focus_area: 'AI Chips',
    technology_area: 'Semiconductors',
    driver_trend: 'US-China Tech Decoupling',
    signal_type: 'strong',
    geographic_relevance: 'China',
    industry_relevance: 'Technology, Defense',
    confidence_level: 3,
    novelty: 4,
    potential_impact: 5,
    time_horizon: '1-2yr',
    status: 'under_review',
    tags: JSON.stringify(['China', 'semiconductor', 'export-controls', 'Huawei', 'geopolitics']),
    analyst_notes: 'Major geopolitical signal. Reassess export control effectiveness assumptions.'
  },
  {
    title: 'Wildfire Prediction AI Achieves 72-Hour Warning Windows in California',
    summary: 'CALFIRE deploys ML-based wildfire prediction system using satellite imagery, weather data, and fuel moisture sensors achieving 72-hour predictive warnings with 87% accuracy. Enabled pre-positioning of 40% more resources.',
    source_name: 'CALFIRE',
    source_type: 'announcement',
    url: 'https://calfire.gov/wildfire-ai-prediction',
    publication_date: '2024-09-15',
    scan_date: '2024-09-16',
    topic_area: 'Climate Technology',
    focus_area: 'Climate Adaptation',
    technology_area: 'Machine Learning',
    driver_trend: 'Climate Resilience',
    signal_type: 'emerging',
    geographic_relevance: 'USA',
    industry_relevance: 'Government, Insurance, Real Estate',
    confidence_level: 4,
    novelty: 4,
    potential_impact: 4,
    time_horizon: 'now',
    status: 'new',
    tags: JSON.stringify(['wildfire', 'prediction', 'climate', 'CALFIRE', 'satellite']),
    analyst_notes: 'Good example of AI for climate adaptation. Insurance industry implications.'
  }
];

function seed(): void {
  initDb();
  const db = getDb();

  const existing = db.prepare('SELECT COUNT(*) as count FROM signals').get() as { count: number };
  if (existing.count > 0) {
    console.log(`Database already has ${existing.count} signals. Skipping seed.`);
    return;
  }

  const insert = db.prepare(`
    INSERT INTO signals (
      title, summary, source_name, source_type, url, publication_date, scan_date,
      topic_area, focus_area, technology_area, driver_trend, signal_type,
      geographic_relevance, industry_relevance, confidence_level, novelty,
      potential_impact, time_horizon, status, tags, analyst_notes
    ) VALUES (
      @title, @summary, @source_name, @source_type, @url, @publication_date, @scan_date,
      @topic_area, @focus_area, @technology_area, @driver_trend, @signal_type,
      @geographic_relevance, @industry_relevance, @confidence_level, @novelty,
      @potential_impact, @time_horizon, @status, @tags, @analyst_notes
    )
  `);

  const insertMany = db.transaction((signals: typeof sampleSignals) => {
    for (const signal of signals) {
      insert.run(signal);
    }
  });

  insertMany(sampleSignals);
  console.log(`Seeded ${sampleSignals.length} sample signals successfully.`);
}

seed();
